# PR pipeline, needs to be in a file named azure-pipelines.yml, located at the root of the projet..

variables:
  clientFolder: client

trigger:
  branches:
    exclude:
      - '*' 

pr:
  branches:
    include:
      - '*'

jobs:
  - job: client_testing
    displayName: Client app testing
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: /.azure/install-steps.yml
        parameters:
          clientFolder: $(clientFolder)

      - script: |
          yarn add -D jest-junit
        workingDirectory: $(clientFolder)
        displayName: 'Install test reporter'
      
      - script : |
          yarn lint
          yarn lint:style
        workingDirectory: $(clientFolder)
        displayName: 'Lint code and styles'

      - script: CI=true yarn test --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura
        workingDirectory: $(clientFolder)
        displayName: 'Run tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(clientFolder)/junit.xml'
      
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage results'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(clientFolder)/coverage/*coverage.xml'