# This script will run the linter, run tests and create a production build.
# It then zips the build folder deploys it to Netlify

variables:
  clientFolder: client

trigger:
  branches:
    include:
      - 'master' 

# Disable for PRs
pr:
  branches:
    exclude:
      - '*'

jobs:
  - job: client_testing
    displayName: Client App Production Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install
          yarn add -D jest-junit
        workingDirectory: $(clientFolder)
        displayName: 'Install dependencies'
      
      - script : |
          yarn lint
          yarn lint:style
        workingDirectory: $(clientFolder)
        displayName: 'Lint code'

      - script: CI=true yarn test --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura
        workingDirectory: $(clientFolder)
        displayName: 'Run tests'

      - script: yarn build
        workingDirectory: $(clientFolder)
        displayName: 'Build project'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(clientFolder)/build'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
        displayName: 'Archive files'

      - script:  >-
            curl
            -H 'Authorization: Bearer $(netlifyAccessToken)' 
            -H 'Content-Type: application/zip'
            --data-binary '@$(Build.BuildId).zip'
            https://api.netlify.com/api/v1/sites/$(netlifySiteId)/deploys
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Upload to Netlify'