variables:
  clientFolder: client

trigger:
  branches:
    include:
      - 'master' 

pr:
  branches:
    exclude:
      - '*'

jobs:
  - job: merge_pipeline
    displayName: Client app production build & deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: install-steps.yml
        parameters:
          clientFolder: $(clientFolder)

      - script: yarn build
        workingDirectory: $(clientFolder)
        displayName: 'Build project'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(clientFolder)/build'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
        displayName: 'Create zip archive'

      - script:  >-
            curl
            -H 'Authorization: Bearer $(netlifyAccessToken)' 
            -H 'Content-Type: application/zip'
            --data-binary '@$(Build.BuildId).zip'
            https://api.netlify.com/api/v1/sites/$(netlifySiteId)/deploys
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Upload to Netlify'
      