variables:
  clientFolder: client

trigger:
  branches:
    exclude:
      - '*' 

pr:
  branches:
    include:
      - '*'

jobs:
  - job: client_testing
    displayName: Client App PR checks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: install-steps.yml
        parameters:
          clientFolder: $(clientFolder)

      - script: |
          yarn add -D jest-junit
        workingDirectory: $(clientFolder)
        displayName: 'yarn add -D jest-junit'
      
      - script : |
          yarn lint
          yarn lint:style
        workingDirectory: $(clientFolder)
        displayName: 'Lint code and styles'

      - script: CI=true yarn test --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura
        workingDirectory: $(clientFolder)
        displayName: 'Run tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(clientFolder)/junit.xml'
      
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(clientFolder)/coverage/*coverage.xml'