export const ADD = 'ADD'
export const TOGGLE = 'TOGGLE'

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM/REQUEST'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM/SUCCESS'
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM/FAILURE'
